// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hodenkgsfdwrwhlpgpnp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhvZGVua2dzZmR3cndobHBncG5wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MzIyMjQsImV4cCI6MjA2NTMwODIyNH0.vD0jV11pzLDOTlsFE57blestZcXHYMvpRAeQCzG7ymk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);